/*
 * generated by Xtext 2.12.0
 */
package de.fhg.aisec.lucon


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LucondslStandaloneSetup extends LucondslStandaloneSetupGenerated {

	def static void doSetup() {
		new LucondslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
